### ISSUE TITLE
store query with dataset

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#10]
Can the query be optionally stored with the dataset.  I realize it won't generate the same list but it is very useful information in figuring out what a dataset is and in making similar sets.

Right now I just reproduce the query in the description but that is clumsy and error prone.

**Comment by ivmfnal** [comment]
I am not sure I see the point. The same query, if repeated, may produce different results. So storing the query with a dataset does not guarantee that the same dataset will be produced by the query again.

Can the query be stored in the dataset metadata ?

**Comment by ivmfnal** [comment]
Besides, I am not sure I see the point in creating datasets, which require the query, by which the dataset was produced, to understand what the dataset is. I need to understand this use case better.
