### ISSUE TITLE
Would be nice for projects to have names and dates in the monitor

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#15]
Samweb has project names and dates which are very useful in figuring out what the heck is going in.  Is it possible to get that feature added to the monitor?  

https://samweb.fnal.gov:8483/station_monitor/dune/stations/dune/projects/

is an example - generally the project name is datasetname+timestamp.

we may need to figure out a good naming convention.

**Comment by ivmfnal** [comment]
Can this be achieved using project metadata ?

**Comment by hschellman** [comment]
Probably - but it would need to be displayed.  Let me look at the metadata to see how one would do this.

On Jan 23, 2023, at 3:31 PM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Can this be achieved using project metadata ?
