### ISSUE TITLE
Possible user interface to find individual files in rucio

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#16]
Would it be possible to use the dd to emulate 

samweb list-file-locations --dim="data_tier raw and run_number 5141" --schema=root

which returns a list of file locations in root format.  dd actually gives a much nicer format for the replicas than that does.  Keep the dd format but it would be good to have a simple way to just get file locations

this would not be a project - just a wrapped query to rucio. 

dd location --query='    '

We anticipate that early in the run, people are going to be wanting to get handles for individual files to do things like event display and it would be good to encourage them to use metacat to find their names and then dd to get their location.  The alternative is having users talk directly to rucio....but dd seems friendlier to me.

**Comment by ivmfnal** [comment]
if you mean DD client, we can think about it
