### ISSUE TITLE
batch jobs don't seem to tell dd the right job site  Fermigrid/FNAL_DCACHE preference is 100. 

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#18]
Ok, so when I run interactively the preferences look good but when I run on batch I get:

looking for files near US_FermiGrid
next_file  {'project_id': 680, 'namespace': 'pdsp_det_reco', 'name': 'np04_raw_run005284_0001_dl3_reco1_14390693_0_20201121T072752
Z.root', 'state': 'reserved', 'worker_id': '964d1aac', 'attempts': 2, 'attributes': {}, 'reserved_since': 1675107397.764603, 'repl
icas': {'LANCASTER': {'name': 'np04_raw_run005284_0001_dl3_reco1_14390693_0_20201121T072752Z.root', 'namespace': 'pdsp_det_reco', 
'path': '/dpm/lancs.ac.uk/home/dune/pdsp_det_reco/ce/1d/np04_raw_run005284_0001_dl3_reco1_14390693_0_20201121T072752Z.root', 'url'
: 'root://fal-pygrid-30.lancs.ac.uk//dpm/lancs.ac.uk/home/dune/pdsp_det_reco/ce/1d/np04_raw_run005284_0001_dl3_reco1_14390693_0_20
201121T072752Z.root', 'rse': 'LANCASTER', 'preference': 100, 'available': True, 'rse_available': True}, 'FNAL_DCACHE': {'name': 'n
p04_raw_run005284_0001_dl3_reco1_14390693_0_20201121T072752Z.root', 'namespace': 'pdsp_det_reco', 'path': '/pnfs/fnal.gov/usr/dune
/tape_backed/dunepro/protodune-sp/full-reconstructed/2020/detector/physics/PDSPProd4/00/00/52/84/np04_raw_run005284_0001_dl3_reco1
_14390693_0_20201121T072752Z.root', 'url': 'root://fndca1.fnal.gov:1094//pnfs/fnal.gov/usr/dune//tape_backed/dunepro/protodune-sp/
full-reconstructed/2020/detector/physics/PDSPProd4/00/00/52/84/np04_raw_run005284_0001_dl3_reco1_14390693_0_20201121T072752Z.root'
, 'rse': 'FNAL_DCACHE', 'preference': 100, 'available': True, 'rse_available': True}}, 'project_attributes': {}} 2023-01-30 19:36:
37.797460

note both preferences are 100.  This indicates that dd is not recognizing fermigrid node as a close-by location.   How should I test/debug this? What does dd use to find where the job site is?

**Comment by ivmfnal** [comment]
Are you setting CPU Site id correctly when you issue "dd worker next" ?

**Comment by ivmfnal** [comment]
DD uses proximity CPU/RSE proximity map: https://metacat.fnal.gov:9443/dune/dd/gui/R/proximity_map

According to the map, default proximity is 100, which means if you enter a non-existing CPU site, you will get the proximity 100 for all RSEs

**Comment by hschellman** [comment]
Problem is that FNAL has 2 sites  US_FermiGrid for grid and US_FNAL for interactive it seems.  Best to list both in the map.

**Comment by ivmfnal** [comment]
The map is maintained by Andrew. DD downloads it automatically from github
