### ISSUE TITLE
FNAL files flagged as not in cache when they are in fact in cache

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#19]
I can open root://fndca1.fnal.gov/pnfs/fnal.gov/usr/dune/tape_backed/dunepro/protodune-sp/full-reconstructed/2020/detector/physics/PDSPProd4/00/00/52/16/np04_raw_run005216_0001_dl11_reco1_38903104_0_20201121T053404Z.root  locally but 

https://metacat.fnal.gov:9443/dune/dd/gui/P/handle?project_id=735&namespace=pdsp_det_reco&name=np04_raw_run005216_0001_dl11_reco1_38903104_0_20201121T053404Z.root

shows it as uncached and so I get a file from the UK instead.  

Could you look into the cache check? 

Thanks, Heidi

**Comment by ivmfnal** [comment]
There was a temporary outage of the dCache pinning interface, which DD did not handle correctly.
It's fixed now

**Comment by hschellman** [comment]
Yep, it's working correctly now.

Thanks
