### ISSUE TITLE
Add a termination to abandoned projects

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#2]
After a given timeout of inactivity can you end (terminate) it. 

States like terminated, dormant, ended.  

Robert also suggests adding a I'm really done status.  

But in my case, the jobs I abandoned can be terminated by the system timeout.

**Comment by ivmfnal** [comment]
Some time ago I introduced the feature of idle project timeout: https://dunescience.slack.com/archives/C948B2KJ6/p1671459448342349
Is this what you were looking for ?

**Comment by hschellman** [comment]
Will need to test - default is 3 days right?

I have a lot of abandoned projects so we will see soon if this work.




On Dec 31, 2022, at 12:53 PM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Some time ago I introduced the feature of idle project timeout: https://dunescience.slack.com/archives/C948B2KJ6/p1671459448342349<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdunescience.slack.com%2Farchives%2FC948B2KJ6%2Fp1671459448342349&data=05%7C01%7Cheidi.schellman%40oregonstate.edu%7Ce1107a01ff12494d140208daeb711e66%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638081168316007926%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SXShuSRKp99TNp3cIta7uL5%2BVuLTCb5afu3Vckar2A4%3D&reserved=0>
Is this what you were looking for ?

**Comment by ivmfnal** [comment]
If they are abandoned, then it does work. Does not it ?

**Comment by hschellman** [comment]
https://metacat.fnal.gov:9443/dune/dd/gui/P/project?project_id=324  is still around .  It dates from the 19th so perhaps before the timeout was implemented.    Earlier ones seem to have gone away.

**Comment by ivmfnal** [comment]
Project 324 has None for idle timeout, which means it will never be abandoned. Most likely the project was created with older version of Data Dispatcher client, which does not set the idle timeout for projects.
