### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is ... Do I need to worry about this? 

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#3]
I've started getting message like this when running the DD with x509 validation and a proxy.  Is this something I should worry about? 

export DATA_DISPATCHER_URL=https://metacat.fnal.gov:9443/dune/dd/data
export DATA_DISPATCHER_AUTH_URL=https://metacat.fnal.gov:8143/auth/dune
export METACAT_SERVER_URL=https://metacat.fnal.gov:9443/dune_meta_demo/app
export METACAT_AUTH_SERVER_URL=https://metacat.fnal.gov:8143/auth/dune

...

Start Project for : files from schellma:run5141recentReco ordered limit 10
Project ID: 236
DDInterface: the query is: files from None limit 1
2022-12-15 12:16:34.197233
/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py:787: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  warnings.warn((
c79127f4

**Comment by ivmfnal** [comment]
That error seems to be coming from /cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py. I am not sure what that is
