### ISSUE TITLE
multiple worker processes on single node

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#6]
The worker ID assignment seems to be independent of the projectID. 

What happens if you are getting input from 2 projects in a single process?  Do things get confused?  This doesn't happen often but it is possible when running simulation to need to run a project for overlay events as well as reading in the geant4 inputs.

**Comment by ivmfnal** [comment]
No DD will not get confused. Same worker ID can be used with multiple projects at the same time.
